# fly.toml app configuration file generated for image-analyzer-broken-sky-469 on 2025-03-16T15:05:26-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'image-analyzer-broken-sky-469'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 8000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
